#!/usr/bin/env python3
"""
Test 2: Visualize HTML output

This test opens the generated HTML file in the default browser for human visual verification.
Since Puppeteer is not available as MCP, this provides a way for humans to inspect the visual output.
"""

import sys
import webbrowser
from pathlib import Path


def test_visualize_html():
    """Open the generated HTML file in the default browser for visual inspection"""
    
    print("🖼️  Starting Test 2: Visualize HTML Output")
    
    # Path to the HTML file generated by test 1
    html_file = Path(__file__).parent / "output" / "test_1_output.html"
    
    # Check if the HTML file exists
    if not html_file.exists():
        print(f"❌ Test 2 FAILED: HTML file not found at {html_file}")
        print("   Please run test 1 first to generate the HTML output")
        return False
    
    # Get file size for verification
    file_size = html_file.stat().st_size
    print(f"📄 HTML file: {html_file}")
    print(f"📏 File size: {file_size} bytes")
    
    # Verify file is not empty
    if file_size == 0:
        print("❌ Test 2 FAILED: HTML file is empty")
        return False
    
    # Read and verify HTML contains slides
    try:
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
        
        # Check for slides (reveal.js uses <section> tags)
        section_count = html_content.count("<section>")
        if section_count == 0:
            print("❌ Test 2 FAILED: HTML does not contain slides")
            return False
        
        # Count slides for user information
        slide_count = section_count
        print(f"🎯 Found {slide_count} slides in HTML")
        
    except Exception as e:
        print(f"❌ Test 2 FAILED: Error reading HTML file: {e}")
        return False
    
    # Open in default browser
    try:
        file_url = html_file.resolve().as_uri()
        print(f"🌐 Opening in browser: {file_url}")
        webbrowser.open(file_url)
        
        print("✅ Test 2 PASSED: HTML opened in browser for visual inspection")
        print("   Please manually verify that:")
        print("   - Slides are displayed correctly")
        print("   - EY Parthenon logo is visible")
        print("   - Content matches the expected report")
        print("   - Visualizations (if any) are rendered properly")
        
        return True
        
    except Exception as e:
        print(f"❌ Test 2 FAILED: Error opening browser: {e}")
        print(f"   You can manually open: {html_file}")
        return False


if __name__ == "__main__":
    success = test_visualize_html()
    sys.exit(0 if success else 1)