#!/usr/bin/env python3
"""
Test 3: HTML to PPTX conversion

This test converts HTML slides to PowerPoint format using the implemented
HTML to PPTX conversion functionality with chart preservation support.
"""

import sys
import asyncio
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

try:
    from slide_generator.tools.html_slides import HtmlDeck, SlideTheme
    from slide_generator.tools.html_to_pptx import HtmlToPptxConverter
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure to install dependencies: pip install python-pptx playwright")
    sys.exit(1)


def test_html_to_pptx_conversion():
    """Test HTML to PPTX conversion functionality"""
    
    print("📄 Starting Test 3: HTML to PPTX Conversion")
    
    # Path to the HTML file generated by test 1
    html_file = Path(__file__).parent / "output" / "test_1_output.html"
    
    # Check if the HTML file exists
    if not html_file.exists():
        print(f"❌ Test 3 FAILED: HTML file not found at {html_file}")
        print("   Please run test 1 first to generate the HTML output")
        return False
    
    # Expected output path for PPTX
    pptx_file = Path(__file__).parent / "output" / "test_1_output.pptx"
    
    print(f"📄 Input HTML: {html_file}")
    print(f"📊 Output PPTX: {pptx_file}")
    
    try:
        # Create a test HTML deck based on the generated content
        # Since we have the HTML file, we'll recreate the deck structure
        # for proper conversion
        success = convert_html_to_pptx(str(html_file), str(pptx_file))
        
        if success:
            # Check if the PPTX file was created and has reasonable size
            if pptx_file.exists():
                file_size = pptx_file.stat().st_size
                print(f"📊 PPTX file created successfully")
                print(f"   File size: {file_size:,} bytes")
                
                if file_size > 10000:  # At least 10KB for a basic presentation
                    print("✅ Test 3 PASSED: HTML to PPTX conversion successful")
                    return True
                else:
                    print("❌ Test 3 FAILED: PPTX file too small, may be corrupt")
                    return False
            else:
                print("❌ Test 3 FAILED: PPTX file was not created")
                return False
        else:
            print("❌ Test 3 FAILED: Conversion function returned False")
            return False
            
    except Exception as e:
        print(f"❌ Test 3 FAILED: Exception during conversion: {str(e)}")
        print(f"   Error type: {type(e).__name__}")
        import traceback
        print(f"   Traceback: {traceback.format_exc()}")
        return False


def convert_html_to_pptx(html_file_path, output_pptx_path):
    """
    Convert HTML file to PPTX format
    
    Args:
        html_file_path: Path to the input HTML file
        output_pptx_path: Path for the output PPTX file
    
    Returns:
        bool: Success status
    """
    try:
        # Create a sample deck that matches the test_1 output structure
        # This recreates the structure for proper conversion
        theme = SlideTheme()
        theme.bottom_right_logo_url = "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjEuMywgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIGhlaWdodD0iMTAwcHgiIHZpZXdCb3g9IjAgMCAzMTAuMzgzMTc4NyAxMDAiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDMxMC4zODMxNzg3IDEwMDsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiMxQTlBRkE7fQoJLnN0MXtmaWxsOiNGRkU2MDA7fQoJLnN0MntmaWxsOiMyRTJFMzg7fQo8L3N0eWxlPgo8Zz4KCTxnPgoJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0xMTcuNDI5NjAzNiw3NS44NTI3MTQ1YzAtMC45NDIxMTU4LTAuMTM5MDk5MS0xLjc4MDc2MTctMC40MTkzMjY4LTIuNTE1MjQzNQoJCQljLTAuMjc5NTYzOS0wLjczNDUyLTAuNjc0OTExNS0xLjM1MzI0MS0xLjE4NjA1MDQtMS44NTY4MzQ0Yy0wLjUxMTEzODktMC41MDI5MjIxLTEuMTI5ODM3LTAuODgxODA1NC0xLjg1NjgxMTUtMS4xMzczNjcyCgkJCWMtMC43MjY5NzQ1LTAuMjU2MjcxNC0xLjUzNzUyMTQtMC4zODQ0MDctMi40MzA5OTk4LTAuMzg0NDA3aC05LjIyMzgwMDd2MTEuODM0OTk5MWg5LjIyMzgwMDcKCQkJYzEuOTc5NDY5MywwLDMuNDU2NzEwOC0wLjUyNzU5NTUsNC40MzE3MTY5LTEuNTgxMzY3NUMxMTYuOTQyNDQzOCw3OS4xNTgwMTI0LDExNy40Mjk2MDM2LDc3LjcwNTQ1MiwxMTcuNDI5NjAzNiw3NS44NTI3MTQ1CgkJCSBNMTIyLjY3NTI4NTMsNzUuODUyNzE0NWMwLDEuNzcyNTY3Ny0wLjI3ODg2OTYsMy4zMjk5NzEzLTAuODM4NjY4OCw0LjY3MDgzNzQKCQkJYy0wLjU1ODM5NTQsMS4zNDE1NjgtMS4zNDA4ODEzLDIuNDYzODgyNC0yLjM0NjcxMDIsMy4zNjYyNzJjLTEuMDA2NTE1NSwwLjkwMjM4MTktMi4yMDQyMDg0LDEuNTg1NDY0NS0zLjU5NDQyMTQsMi4wNDc5ODg5CgkJCWMtMS4zODg4NDc0LDAuNDYzODU5Ni0yLjkyMTU3NzUsMC42OTQ3NDc5LTQuNTk4ODg0NiwwLjY5NDc0NzloLTguOTgzOTg1OXYxMi44MTYxNjk3aC01LjA1NDUxMnYtMzQuMzUxODZoMTQuMzc0MjUyMwoJCQljMS41ODAwMDk1LDAsMy4wNDU1NzgsMC4yMjc1MDA5LDQuMzk2MDU3MSwwLjY4MjQ1N2MxLjM0ODQzNDQsMC40NTU2MTk4LDIuNTE1MjY2NCwxLjEyOTgzNywzLjQ5NzEyMzcsMi4wMjM5ODY4CgkJCWMwLjk4MTg2NDksMC44OTQ4NTE3LDEuNzUyNjg1NSwyLjAxNjQ1NjYsMi4zMTEwODA5LDMuMzY2MjcyCgkJCUMxMjIuMzk2NDE1Nyw3Mi41MTkzNTU4LDEyMi42NzUyODUzLDc0LjA3OTUyMTIsMTIyLjY3NTI4NTMsNzUuODUyNzE0NSIvPgoJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0xNDAuMzMyNTUsODguNDUzMzkyYy0wLjQ3ODk0MjktMC4yMjQwNzUzLTAuOTA5OTEyMS0wLjM5NTM2MjktMS4yOTQyOTYzLTAuNTE1MjY2NAoJCQljLTAuMzgyMzM5NS0wLjExOTg5NTktMC43ODExMTI3LTAuMjIyNjg2OC0xLjE5NzcwODEtMC4zMTEwNTA0Yy0wLjQxNDUwNS0wLjA4NzY5OTktMC45MTQwMDE1LTAuMTU5NjY4LTEuNDk2Mzk4OS0wLjIxNTgzNTYKCQkJYy0wLjU4MzA5OTQtMC4wNTU0ODg2LTEuMjE4MjQ2NS0wLjA4MzU5NTMtMS45MDQ3ODUyLTAuMDgzNTk1M2MtMS42MjkzMzM1LDAtMi45MTg4Mzg1LDAuMzQzOTcxMy0zLjg2Nzc5NzksMS4wMjk4MDgKCQkJYy0wLjk1MTcwNTksMC42ODY1NTQtMS40MjUxNzA5LDEuNjIxODEwOS0xLjQyNTE3MDksMi44MDMwNDcyYzAsMC43NjYwNTIyLDAuMTM0MzA3OSwxLjQxNjkzMTIsMC40MDY5OTc3LDEuOTUyMDU2OQoJCQljMC4yNzA2NDUxLDAuNTM1MTI1NywwLjYxNDU5MzUsMC45NzA4ODYyLDEuMDI5ODMwOSwxLjMwNTI3NWMwLjQxNDUwNSwwLjMzNTA2MDEsMC45MDY0Nzg5LDAuNTg3ODYwMSwxLjQ3MjQyNzQsMC43NTU3MjIKCQkJYzAuNTY3MzIxOCwwLjE2NzE5ODIsMS4yNDkwNjkyLDAuMjUwNzkzNSwyLjA0ODY2MDMsMC4yNTA3OTM1YzAuNjcwNzc2NCwwLDEuMzE3NTgxMi0wLjA5NTkzMiwxLjk0MDM5OTItMC4yODc3NjU1CgkJCWMwLjYyMzUxOTktMC4xOTExOTI2LDEuMjA1MjMwNy0wLjQ0MjYxMTcsMS43NDg1NjU3LTAuNzU0Mzc5M2MwLjU0MjY3ODgtMC4zMTEwOTYyLDEuMDI5ODMwOS0wLjY2MTg4MDUsMS40NjE0NzE2LTEuMDUzODE3NwoJCQljMC40MzIzNTc4LTAuMzkxMjIwMSwwLjc5MDcxMDQtMC43ODY1ODI5LDEuMDc3ODA0Ni0xLjE4NjAwNDZWODguNDUzMzkyeiBNMTQwLjMzMjU1LDk5LjQ0OTAyOHYtMi41MzkyNDU2CgkJCWMtMC42NTQzNTc5LDAuNjA3NzY1Mi0xLjE5NzY5MjksMS4wNTAzODQ1LTEuNjI5MzY0LDEuMzI5MjMxM2MtMC40MzA5NjkyLDAuMjc5NTYzOS0wLjg3NzcxNjEsMC41NDMzNjU1LTEuMzQxNTY4LDAuNzkxMzk3MQoJCQljLTAuNDYyNDkzOSwwLjI0NjY1MDctMS4wNDk2ODI2LDAuNDcwMDA4OS0xLjc2MDIwODEsMC42NzAwNzQ1Yy0wLjcxMDUyNTUsMC4xOTk0MDE5LTEuNDg4ODYxMSwwLjI5OTQzMDgtMi4zMzUwNjc3LDAuMjk5NDMwOAoJCQljLTEuMDM4NzExNSwwLTIuMDg5MDk2MS0wLjE1NTUyNTItMy4xNTA0MjExLTAuNDY3MjkyOGMtMS4wNjMzODUtMC4zMTEwNTA0LTIuMDIwNTg0MS0wLjgxMzk4MDEtMi44NzQzMDU3LTEuNTA4NzI4CgkJCWMtMC44NTUwODczLTAuNjk1NDU3NS0xLjU1Mzk3OC0xLjU5MzAzMjgtMi4wOTczMTI5LTIuNjk1NDgwM2MtMC41NDI2NTU5LTEuMTAxNzM4LTAuODEzMjkzNS0yLjQ0MzMxMzYtMC44MTMyOTM1LTQuMDI0NjgxMQoJCQljMC0xLjQzNjg0MzksMC4yNTgzMDA4LTIuNjc5MDU0MywwLjc3NzY1NjYtMy43MjQ2MjQ2YzAuNTE4NjkyLTEuMDQ2MjQ5NCwxLjIzNzQyNjgtMS45MTIzMzA2LDIuMTU1NTU1Ny0yLjU5ODgzODgKCQkJYzAuOTE5NTA5OS0wLjY4NzI2MzUsMi4wMDU1MDg0LTEuMTk0MjkwMiwzLjI1ODY4MjMtMS41MjE3NzQzYzEuMjUzODYwNS0wLjMyNjgyMDQsMi42MDcwODYyLTAuNDkxMzAyNSw0LjA2MDMzMzMtMC40OTEzMDI1CgkJCWMxLjM1NzM0NTYsMCwyLjQ5ODg0MDMsMC4wOTI1MDY0LDMuNDI1MTg2MiwwLjI3NjEzODNjMC45MjYzNjExLDAuMTgyOTYwNSwxLjcwMTI3ODcsMC40MTg2NTU0LDIuMzI0MTI3MiwwLjcwNjQxMzN2LTEuOTE3MDkxNAoJCQljMC0xLjQwNDY0MDItMC40MTQ1NTA4LTIuNDgyNDE0Mi0xLjI0NDk3OTktMy4yMzMzNjc5Yy0wLjgzMDQyOTEtMC43NTAyNDQxLTIuMDM3NzA0NS0xLjEyNTcwMTktMy42MTgzOTI5LTEuMTI1NzAxOQoJCQljLTEuMzI1ODIwOSwwLTIuNTIyODExOSwwLjEyNzQxODUtMy41OTM3MzQ3LDAuMzgyOTgwM2MtMS4wNjg4NjI5LDAuMjU1NTYxOC0yLjEwNzU4OTcsMC42NjI1OS0zLjExMzQzMzgsMS4yMjIzNTExCgkJCWwtMS45NjQzOTM2LTMuODA5NTYyN2MxLjIyOTIwOTktMC43NjY2Nzc5LDIuNTUxNTgyMy0xLjM0NTAwMTIsMy45NjM3Mzc1LTEuNzM2ODkyNwoJCQljMS40MTQ4NzEyLTAuMzkxMjI3NywzLjAzMTIwNDItMC41ODcxODg3LDQuODUxNzE1MS0wLjU4NzE4ODdjMS40MzY3OTgxLDAsMi43NTA5NjEzLDAuMTc2MDU1OSwzLjk0MTEwMTEsMC41Mjc1NDk3CgkJCWMxLjE4OTQ2ODQsMC4zNTE0OTM4LDIuMjA3NjQxNiwwLjg4NTk0ODIsMy4wNTQ1MTk3LDEuNjA1Mzc3MmMwLjg0NjE3NjEsMC43MTgwNzg2LDEuNTA1MzEwMSwxLjYyMDQyMjQsMS45NzYwMjg0LDIuNzA2NDM2MgoJCQljMC40NzEzODk4LDEuMDg2Njg1MiwwLjcwNjQyMDksMi4zNTU2MjEzLDAuNzA2NDIwOSwzLjgwODg5MTNWOTkuNDQ5MDI4SDE0MC4zMzI1NXoiLz4KCQk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMTY0LjE3MTcwNzIsNzkuMDM5MDMyYy0wLjU0MzM2NTUtMC4zMDM1Mjc4LTEuMTE0NzkxOS0wLjUzNTA4LTEuNzEyOTM2NC0wLjY5NDc0NzkKCQkJYy0wLjU5OTUzMzEtMC4xNTk2MjIyLTEuMzEzNDkxOC0wLjIzOTEyMDUtMi4xNDM5MjA5LTAuMjM5MTIwNWMtMS42MTI4ODQ1LDAtMi44NTk5MDkxLDAuNTU0MzEzNy0zLjczNzYwOTksMS42NjM1ODE4CgkJCWMtMC44Nzg0MDI3LDEuMTExMzU4Ni0xLjMxNjkwOTgsMS43Njc0MTc5LTEuMzE2OTA5OCw0Ljk3MDkzMnYxNC43MDkzMDQ4aC01LjA1NTE5MVY3My42OTY3NDY4aDUuMDU1MTkxdjIuNDQzMzUxNwoJCQljMC4yODcwOTQxLTAuNDMwOTkyMSwwLjYzNzg5MzctMC44MjYzMTY4LDEuMDUzODAyNS0xLjE4NjA1MDRjMC40MTU4OTM2LTAuMzU4MzUyNywwLjg3NDI4MjgtMC42NzQyMTcyLDEuMzc3MTk3My0wLjk0NjIwNTEKCQkJYzAuNTAyODk5Mi0wLjI3MTMzMTgsMS4wNDIxNDQ4LTAuNDgyMzkxNCwxLjYxNzY5MS0wLjYzNTE2MjRjMC41NzQxODgyLTAuMTUwNzU2OCwxLjE4MTI0MzktMC4yMjc0OTMzLDEuODIxMTgyMy0wLjIyNzQ5MzMKCQkJYzEuMDM2NjY2OSwwLDEuODk5MzA3MywwLjA5NTkzMiwyLjU4NjU0NzksMC4yODc3OTZjMC42ODU4MzY4LDAuMTkxODMzNSwxLjI4NTM2OTksMC40NTQ5NTYxLDEuNzk2NTA4OCwwLjc5MDY4NzYKCQkJTDE2NC4xNzE3MDcyLDc5LjAzOTAzMnoiLz4KCQk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMTgyLjg3NzQ1NjcsOTguODAyMDMyNWMtMC42MjI4MzMzLDAuMzUxNDkzOC0xLjM1MzkxMjQsMC42Mzk5Njg5LTIuMTkxMTkyNiwwLjg2MjY1NTYKCQkJYy0wLjgzODY1MzYsMC4yMjMzNTgyLTEuNzYwODc5NSwwLjMzNTA2MDEtMi43NjY3MjM2LDAuMzM1MDYwMWMtMC44NzkwNzQxLDAtMS42NTA1ODktMC4xMjQwMzg3LTIuMzEyNDY5NS0wLjM3MDY4OTQKCQkJYy0wLjY2MjU1MTktMC4yNDczNjAyLTEuMjY2MTg5Ni0wLjYzOTI1MTctMS44MDg4Mzc5LTEuMTc0Mzc3NGMtMC41NDMzNTAyLTAuNTM1MTI1Ny0wLjk1Nzg4NTctMS4yMzc0NDItMS4yNDQ5Nzk5LTIuMTA3NTgyMQoJCQljLTAuMjg3NzUwMi0wLjg3MDg1NzItMC40MzE2NTU5LTEuOTI4NzY0My0wLjQzMTY1NTktMy4xNzQ0MDhWNzguMjk2MTk2aC0zLjY2NTY2NDd2LTQuNTk5NTc4OWgzLjY2NTY2NDd2LTcuMzU0NjUyNAoJCQlsNC45NTc5MzE1LTIuNjU5MTQxNXYxMC4wMTM3OTM5aDYuMzczNDc0MXY0LjU5OTU3ODloLTYuMzczNDc0MXYxMy45ODk4NzU4YzAsMC42MDcwNTU3LDAuMDUyMDYzLDEuMTA1ODQyNiwwLjE1NjkwNjEsMS40OTc3NzIyCgkJCWMwLjEwMzQ1NDYsMC4zOTEyMjAxLDAuMjYzMDc2OCwwLjcwNjQyMDksMC40Nzg5MTI0LDAuOTQ2MjEyOGMwLjIxNTE2NDIsMC4yMzkxMjA1LDAuNDkwNTg1MywwLjQwNjMxODcsMC44MjYzMzk3LDAuNTAyMjUwNwoJCQljMC4zMzUwMzcyLDAuMDk2NjAzNCwwLjczNDQ5NzEsMC4xNDQ1NywxLjE5NzY3NzYsMC4xNDQ1N2MwLjY1NTAxNCwwLDEuMzIxNzAxLTAuMTAzNDYyMiwyLjAwMDcwMTktMC4zMTE3Njc2CgkJCWMwLjY3NzYyNzYtMC4yMDc1OTU4LDEuMjQ5MDY5Mi0wLjQ0NjcxNjMsMS43MTI5MzY0LTAuNzE4NzU3NkwxODIuODc3NDU2Nyw5OC44MDIwMzI1eiIvPgoJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0yMDMuODAyMDE3Miw5OS40NDkwMjhWODQuODg0MzMwN2MwLTIuMzc5NjE1OC0wLjQyMjc0NDgtNC4xNTIxNDU0LTEuMjcwMzA5NC01LjMxODk5MjYKCQkJYy0wLjg0NjE5MTQtMS4xNjU0NzM5LTIuMTg3Nzc0Ny0xLjc0ODU2NTctNC4wMjQ3MTkyLTEuNzQ4NTY1N2MtMC43ODE3ODQxLDAtMS41MDQ2MjM0LDAuMTI4MTM1Ny0yLjE2ODU2MzgsMC4zODM2OTc1CgkJCWMtMC42NjE4ODA1LDAuMjU1NTU0Mi0xLjIyOTIwMjMsMC42Nzg5NzgtMS42OTk5MjA3LDEuMjY5NTk5OWMtMC40NzEzODk4LDAuNTkwNjIxOS0wLjgyNjMwOTIsMS4yODU0MDgtMS4wNjY4MDMsMi4wODQzMzUzCgkJCWMtMC4yMzg0NDkxLDAuNzk4MjEwMS0wLjM1ODM1MjcsMS43NDA5ODk3LTAuMzU4MzUyNywyLjgyNzAwMzVWOTkuNDQ5MDI4aC01LjA1NDUxOTdWNjYuMzQyMTcwN2w1LjA1NDUxOTctMi42NTkxNDE1VjYuMTM5NDczCgkJCWMwLjMxOTk2MTUtMC40NjE4MTQ5LDAuNzEwNTI1NS0wLjg4MTgxMywxLjE3MzY5MDgtMS4yNTY1OTk0YzAuNDYzODY3Mi0wLjM3NTQ5NTksMC45NzQzMzQ3LTAuNjkwNjk2NywxLjUzNDExODctMC45NDYyNTA5CgkJCWMwLjU1NzcyNC0wLjI1NDg5MDQsMS4xNTcyNDE4LTAuNDUxNTMwNSwxLjc5NTgzNzQtMC41ODcxODg3YzAuNjM4NTgwMy0wLjEzNTY2NTksMS4yOTM2MDk2LTAuMjA0MTYyNiwxLjk2NDM4Ni0wLjIwNDE2MjYKCQkJYzEuNTQ4NDc3MiwwLDIuODkwMDYwNCwwLjI0ODAzMTYsNC4wMjQwMTczLDAuNzQyNzEzOWMxLjEzMzk1NjksMC40OTUzOTE4LDIuMDg4NDA5NCwxLjIyNTc3NjcsMi44NjMzNDIzLDIuMTkyNTU4MwoJCQljMC43NzQyNjE1LDAuOTY2Nzg5MiwxLjM0OTEwNTgsMi4xOTU5OTE1LDEuNzI1MjgwOCwzLjY4ODI4NThjMC4zNzQ3ODY0LDEuNDkzNjc1MiwwLjU2MjUxNTMsMy4xMzUzNDU1LDAuNTYyNTE1Myw0LjkyMzYzNzQKCQkJVjk5LjQ0OTAyOEgyMDMuODAyMDE3MnoiLz4KCQk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjI5LjY0NDY4MzgsODQuMTg4OTU3MmMtMC4wNjQ0MDczLTAuODc4Mzc5OC0wLjIxOTk0MDItMS43MDg4MzE4LTAuNDY2NTgzMy0yLjQ5MDYwODIKCQkJYy0wLjI0ODcwMy0wLjc4MzE1NzMtMC42MTQ1OTM1LTEuNDY5NzExMy0xLjEwMjQ0NzUtMi4wNjAzMzMzYy0wLjQ4NzgzODctMC41OTA2MTQzLTEuMTAxNzQ1Ni0xLjA1Nzg2OS0xLjg0Mzc5NTgtMS40MDE4MzI2CgkJCWMtMC43NDM0MjM1LTAuMzQzMjk5OS0xLjYzMzQ2ODYtMC41MTUyNTg4LTIuNjcxNDc4My0wLjUxNTI1ODhjLTAuODk0ODUxNywwLTEuNjc2NjM1NywwLjE0ODY2NjQtMi4zNDg4MDA3LDAuNDQzMjgzMQoJCQljLTAuNjY5NDAzMSwwLjI5NjAwNTItMS4yNDQ5NjQ2LDAuNzE0NjYwNi0xLjcyMzg5MjIsMS4yNTczMDljLTAuNDc4OTEyNCwwLjU0MzM2NTUtMC44NzQyODI4LDEuMjEwNzIzOS0xLjE4NjAzNTIsMi4wMDA2OTQzCgkJCWMtMC4zMTEwNjU3LDAuNzkxMzk3MS0wLjUyMzQ2OCwxLjcxMjkyODgtMC42MzUxNjI0LDIuNzY2NzQ2NUgyMjkuNjQ0NjgzOHogTTIzNC43NDc4NzksODYuMDU4MDgyNgoJCQljMCwwLjQ2MzE5NTgtMC4wMTY0NjQyLDAuODk0MTg3OS0wLjA0ODY3NTUsMS4yOTM2MDk2Yy0wLjAzMjE5NiwwLjM5OTQ1OTgtMC4wNjQzOTIxLDAuNzM0NTItMC4wOTUyMTQ4LDEuMDA1MTcyN2gtMTcuMDMyNzMwMQoJCQljMC4xNDM5MDU2LDEuMjQ2MzE1LDAuNDE1MjM3NCwyLjMxMjQ2MTksMC44MTQ2OTczLDMuMTk5MDgxNGMwLjM5ODA3MTMsMC44ODU5MSwwLjg4NTkxLDEuNjE2OTk2OCwxLjQ2MDA4MywyLjE5MTg0ODgKCQkJYzAuNTc2MjMyOSwwLjU3NDg1MiwxLjIyNzE1NzYsMC45OTgzMjE1LDEuOTU0MTE2OCwxLjI2OTY0NTdjMC43MjYyNzI2LDAuMjcxOTk1NSwxLjQ4MDY2NzEsMC40MDY5OTAxLDIuMjYzMTA3MywwLjQwNjk5MDEKCQkJYzAuNTU4NDEwNiwwLDEuMDg2MDEzOC0wLjA0NzMwMjIsMS41ODA3MDM3LTAuMTQzOTA1NmMwLjQ5NTM5MTgtMC4wOTU5MzIsMC45NzAyMTQ4LTAuMjM5NzkxOSwxLjQyNTE3MDktMC40MzA5NDY0CgkJCWMwLjQ1NTYxMjItMC4xOTEyMDAzLDAuODU4NTA1Mi0wLjM4NjQ1OTQsMS4yMTA3MDg2LTAuNTg2NTI1YzAuMzUwMTEyOS0wLjIwMDA2NTYsMC44MDU3NDA0LTAuNDk5NDg4OCwxLjM2NDgzNzYtMC44OTg5NDg3CgkJCWwyLjk5NDkwMzYsMy4yMzQ3MDMxYy0wLjYzOTI1MTcsMC42MDcwNTU3LTEuMjQ5NzQwNiwxLjA5NzY0MS0xLjgzMjgyNDcsMS40NzI0Mjc0CgkJCWMtMC41ODM3NTU1LDAuMzc2MTY3My0xLjIxMzQzOTksMC43MTEyMjc0LTEuODkzMTI3NCwxLjAwNjUxNTVjLTAuNjc5MDMxNCwwLjI5NTMzMzktMS40NDkxNDI1LDAuNTIzNDk4NS0yLjMxMTA4MDksMC42ODI0NTcKCQkJQzIyNS43NDA1NzAxLDk5LjkxOTgzMDMsMjI0Ljc4ODg3OTQsMTAwLDIyMy43NTE1NDExLDEwMGMtMS4xMTgyMjUxLDAtMi4xNjQ0NTkyLTAuMTU1NTI1Mi0zLjEzODEwNzMtMC40NjcyOTI4CgkJCWMtMC45NzQzMTk1LTAuMzExMDU4LTEuODM2OTc1MS0wLjcxODc1NzYtMi41ODY1NDc5LTEuMjIxNjMzOWMtMC43NTE2MTc0LTAuNTAzNjMxNi0xLjQyNjUxMzctMS4wNzc3NzQtMi4wMjQ2NTgyLTEuNzI1MjczMQoJCQljLTAuNTk5NTE3OC0wLjY0NjExMDUtMS4xNjk1ODYyLTEuNDc2NTYyNS0xLjcxMjkyMTEtMi40OTEzMTc3Yy0wLjU0MzM1MDItMS4wMTMzNzQzLTAuOTU3ODg1Ny0yLjE0NzMxNi0xLjI0NTY1MTItMy40MDExOTE3CgkJCWMtMC4yODc3ODA4LTEuMjUzMTY2Mi0wLjQzMTY1NTktMi42MjI4NDA5LTAuNDMxNjU1OS00LjEwODI3NjRjMC0yLjE3MTMxODEsMC4yNzU0MjExLTQuMDk2NjU2OCwwLjgyNjk5NTgtNS43NzMyODQ5CgkJCWMwLjU1MDg3MjgtMS42NzY1OSwxLjMyMDk5OTEtMy4wODE5MDE2LDIuMzExMDgwOS00LjIxNzIxNjVjMC45OTE0Mzk4LTEuMTMzMjcwMywyLjE4MDIwNjMtMS45OTExMTk0LDMuNTY5MDc2NS0yLjU3NDIxMTEKCQkJYzEuMzkwODg0NC0wLjU4MzA5MTcsMi45MTQ3MDM0LTAuODc0OTU0Miw0LjU3NjI0ODItMC44NzQ5NTQyYzEuODM2OTU5OCwwLDMuNDM0MDk3MywwLjM0ODA2ODIsNC43OTE0NDI5LDEuMDQyODE2MgoJCQljMS4zNTcyOTk4LDAuNjk0MDg0MiwyLjQ4MjM2MDgsMS42Mjg2Njk3LDMuMzc3ODk5MiwyLjgwMjM3NThjMC44OTQ4MDU5LDEuMTczNjY3OSwxLjU2NDIyNDIsMi41NDQwMTQsMi4wMTIzNTk2LDQuMTA4OTQ3OAoJCQlDMjM0LjUyMzE0NzYsODIuNjY0NDY2OSwyMzQuNzQ3ODc5LDg0LjMxNzc2NDMsMjM0Ljc0Nzg3OSw4Ni4wNTgwODI2Ii8+CgkJPHBhdGggY2xhc3M9InN0MCIgZD0iTTI1NC4xNDU1MDc4LDk5LjQ0OTAyOFY4NC44ODQzMzA3YzAtMi4zMzE2NDk4LTAuNDE0NTUwOC00LjA5MTg0MjctMS4yNDQ5NjQ2LTUuMjgzMzYzMwoJCQljLTAuODI5NzQyNC0xLjE4ODc2NjUtMi4xODAyMzY4LTEuNzg0MTk0OS00LjA0ODY5MDgtMS43ODQxOTQ5Yy0wLjgxMzk4MDEsMC0xLjU2NDkyNjEsMC4xNDQ1Njk0LTIuMjUyMTUxNSwwLjQzMTY2MzUKCQkJYy0wLjY4NjU1NCwwLjI4Nzc1NzktMS4yNjE0MTM2LDAuNzM0NDc0Mi0xLjcyNDYwOTQsMS4zNDE1NzU2Yy0wLjQ2Mzg1MTksMC42MDYzMzg1LTAuNzk4OTE5NywxLjMyMDk5OTEtMS4wMDU4NDQxLDIuMTQzODgyOAoJCQljLTAuMjA4MjUyLDAuODIyODgzNi0wLjMxMTcyMTgsMS43MDQ3MzQ4LTAuMzExNzIxOCwyLjY0NzUxNDNWOTkuNDQ5MDI4aC01LjA1NDUzNDlWNzMuNjk2ODIzMWg1LjA1NDUzNDl2Mi40NDI2NDk4CgkJCWMwLjMxOTk2MTUtMC40NjE4MTQ5LDAuNzExMTgxNi0wLjg4MTgxMywxLjE3MzY3NTUtMS4yNTY1OTk0YzAuNDYzMTk1OC0wLjM3NTQ5NTksMC45NzQzMDQyLTAuNjkwNjk2NywxLjUzNDEwMzQtMC45NDYyNTA5CgkJCWMwLjU1Nzc1NDUtMC4yNTQ4OTA0LDEuMTU3MjcyMy0wLjQ1MTUzMDUsMS43OTU4Njc5LTAuNTg3MTg4N2MwLjYzOTI1MTctMC4xMzU2NjU5LDEuMjk0MjY1Ny0wLjIwNDE2MjYsMS45NjQzODYtMC4yMDQxNjI2CgkJCWMxLjU0OTE2MzgsMCwyLjg5NDgzNjQsMC4yNTI3OTI0LDQuMDM2MzQ2NCwwLjc1NTA1MDdjMS4xNDI4NTI4LDAuNTAyOTIyMSwyLjA5MTgxMjEsMS4yMjU3NzY3LDIuODUxNjk5OCwyLjE2Nzg4NDgKCQkJYzAuNzU3ODEyNSwwLjk0MjExNTgsMS4zMjg1MjE3LDIuMTMyMjYzMiwxLjcxMjIxOTIsMy41Njk3NzA4YzAuMzgzMDI2MSwxLjQzNzQ2MTksMC41NzU1NjE1LDMuMTIyMjkxNiwwLjU3NTU2MTUsNS4wNTQ0ODkxCgkJCVY5OS40NDkwMjhIMjU0LjE0NTUwNzh6Ii8+CgkJPHBhdGggY2xhc3M9InN0MCIgZD0iTTI4MC44Mjc5MTE0LDg2LjU4NDcxNjhjMC0xLjMwOTM3MTktMC4xNTI3NzEtMi40OTUzNzY2LTAuNDU1NjI3NC0zLjU1NzQyNjUKCQkJYy0wLjMwMzUyNzgtMS4wNjEzMDIyLTAuNzM4NjE2OS0xLjk2Nzc4MTEtMS4zMDU5Mzg3LTIuNzE4NzM0N2MtMC41NjY2ODA5LTAuNzUwMjg5OS0xLjI1NzMyNDItMS4zMjk5NDg0LTIuMDcxOTYwNC0xLjczNjkzODUKCQkJYy0wLjgxMzk5NTQtMC40MDY5OTAxLTEuNzMzNTIwNS0wLjYxMDQ4MTMtMi43NTUwOTY0LTAuNjEwNDgxM2MtMC45NTg1ODc2LDAtMS44MTcwNzc2LDAuMjAzNDkxMi0yLjU3NTU2MTUsMC42MTA0ODEzCgkJCWMtMC43NTc3ODIsMC40MDY5OTAxLTEuNDA1MjczNCwwLjk4MTg4MDItMS45Mzk3Mjc4LDEuNzI0NjAxN2MtMC41MzUxMjU3LDAuNzQyNzEzOS0wLjk0NjIyOCwxLjYzMzQzMDUtMS4yMzM5NzgzLDIuNjcxNDc4MwoJCQljLTAuMjg3ODExMywxLjAzODA0NzgtMC40MzAzMjg0LDIuMTk1OTkxNS0wLjQzMDMyODQsMy40NzMxMjE2YzAsMS40MjE3NDUzLDAuMTU1NTc4NiwyLjY3NDk0OTYsMC40NjY2MTM4LDMuNzYwOTI1MwoJCQljMC4zMTEwNjU3LDEuMDg2Njg1MiwwLjc1MDI0NDEsMS45OTY1ODk3LDEuMzE3NTk2NCwyLjczMTc4MWMwLjU2NjY1MDQsMC43MzQ1MiwxLjI0NTYzNiwxLjI5MjkzODIsMi4wMzYzNDY0LDEuNjc2NjM1NwoJCQljMC43OTA2Nzk5LDAuMzgyMzE2NiwxLjY2NDI0NTYsMC41NzQ4NTIsMi42MjI4NjM4LDAuNTc0ODUyYzAuOTU3ODI0NywwLDEuODIzOTEzNi0wLjIyNzQ1NTEsMi41OTg4MTU5LTAuNjgyNDExMgoJCQljMC43NzQyNjE1LTAuNDU1NjY1NiwxLjQzODIwMTktMS4wNzA5NjEsMS45ODkwNzQ3LTEuODQ1MTY5MWMwLjU1MDE3MDktMC43NzQ5NTU3LDAuOTc3NzUyNy0xLjY4NDg2NzksMS4yODEyODA1LTIuNzMwNDQ1OQoJCQlDMjgwLjY3NTE0MDQsODguODgwNzQ0OSwyODAuODI3OTExNCw4Ny43NjczMzQsMjgwLjgyNzkxMTQsODYuNTg0NzE2OCBNMjg1LjkyOTcxOCw4Ni40NDA4MTg4CgkJCWMwLDIuMTQwNDk1My0wLjI5NTMxODYsNC4wNDg3Mjg5LTAuODg1OTI1Myw1LjcyNTMxODljLTAuNTkxMzA4NiwxLjY3NzI5OTUtMS40MDU5NzUzLDMuMDk4MzczNC0yLjQ0NDAzMDgsNC4yNjQ1MTExCgkJCWMtMS4wMzc5OTQ0LDEuMTY2MTgzNS0yLjI2NzkxMzgsMi4wNTIwOTM1LTMuNjg4OTY0OCwyLjY1OTE4NzNjLTEuNDIxMDUxLDAuNjA3MDU1Ny0yLjk1NDQ2NzgsMC45MDk4NzQtNC41OTg5MDc1LDAuOTA5ODc0CgkJCWMtMS42MjkzMzM1LDAtMy4xMzUzNDU1LTAuMzE5MjUyLTQuNTE2NjMyMS0wLjk1Nzg0Yy0xLjM4MDY0NTgtMC42Mzg1ODgtMi41NzgzMDgxLTEuNTQ1MDY2OC0zLjU5MjM0NjItMi43MTk0NDQzCgkJCWMtMS4wMTQ3NzA1LTEuMTczNzEzNy0xLjgxMDI0MTctMi41ODY1NDc5LTIuMzg0NDI5OS00LjIzOTg5MTFjLTAuNTc0MTU3Ny0xLjY1MzI5NzQtMC44NjE5Mzg1LTMuNDg1NDUwNy0wLjg2MTkzODUtNS40OTc4MTgKCQkJYzAtMi4xMDc1ODIxLDAuMjk0NjQ3Mi0zLjk5MjQ3NzQsMC44ODU5MjUzLTUuNjUzMzQzMmMwLjU5MTMwODYtMS42NjA4NjU4LDEuNDAxODg2LTMuMDcwMjc0NCwyLjQzMTcwMTctNC4yMjgyMTgxCgkJCWMxLjAyOTgxNTctMS4xNTcyMzQyLDIuMjQzODk2NS0yLjAzOTc0OTEsMy42NDE2OTMxLTIuNjQ2ODA0OGMxLjM5NzA2NDItMC42MDcwOTM4LDIuOTEwNjE0LTAuOTEwNjIxNiw0LjUzOTk0NzUtMC45MTA2MjE2CgkJCWMxLjY0NDQwOTIsMCwzLjE2NDgyNTQsMC4zMTU4NjQ2LDQuNTYyNTYxLDAuOTQ2OTIyM2MxLjM5ODQzNzUsMC42MzAzNDgyLDIuNjA3Nzg4MSwxLjUyNDQ5MDQsMy42MzAwNjU5LDIuNjgyNDM0MQoJCQljMS4wMjE1NzU5LDEuMTU3OTQzNywxLjgyMzkxMzYsMi41NTUwMTU2LDIuNDA3MDEyOSw0LjE5MjU4ODgKCQkJQzI4NS42Mzc4MTc0LDgyLjYwMzg2NjYsMjg1LjkyOTcxOCw4NC40Mjg0OTczLDI4NS45Mjk3MTgsODYuNDQwODE4OCIvPgoJCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0zMDUuMzI4NzA0OCw5OS40NDkwMjhWODQuODg0MzMwN2MwLTIuMzMxNjQ5OC0wLjQxNDU4MTMtNC4wOTE4NDI3LTEuMjQ2MzY4NC01LjI4MzM2MzMKCQkJYy0wLjgyOTc0MjQtMS4xODg3NjY1LTIuMTc4ODMzLTEuNzg0MTk0OS00LjA0ODY3NTUtMS43ODQxOTQ5Yy0wLjgxMzMyNCwwLTEuNTY0OTQxNCwwLjE0NDU2OTQtMi4yNTE0OTU0LDAuNDMxNjYzNQoJCQljLTAuNjg3MjI1MywwLjI4Nzc1NzktMS4yNjA2ODEyLDAuNzM0NDc0Mi0xLjcyNDU0ODMsMS4zNDE1NzU2Yy0wLjQ2MzE5NTgsMC42MDYzMzg1LTAuNzk4MjQ4MywxLjMyMDk5OTEtMS4wMDU4NTk0LDIuMTQzODgyOAoJCQljLTAuMjA3NTgwNiwwLjgyMjg4MzYtMC4zMTEwMzUyLDEuNzA0NzM0OC0wLjMxMTAzNTIsMi42NDc1MTQzVjk5LjQ0OTAyOGgtNS4wNTU5Mzg3VjczLjY5NjgyMzFoNS4wNTU5Mzg3djIuNDQyNjQ5OAoJCQljMC4zMTg1NzMtMC40NjE4MTQ5LDAuNzA5Nzc3OC0wLjg4MTgxMywxLjE3MzY0NS0xLjI1NjU5OTRjMC40NjMxOTU4LTAuMzc1NDk1OSwwLjk3NDMzNDctMC42OTA2OTY3LDEuNTMyNzQ1NC0wLjk0NjI1MDkKCQkJYzAuNTU4NDEwNi0wLjI1NDg5MDQsMS4xNTc5Mjg1LTAuNDUxNTMwNSwxLjc5NzI0MTItMC41ODcxODg3YzAuNjM3ODc4NC0wLjEzNTY2NTksMS4yOTI4NzcyLTAuMjA0MTYyNiwxLjk2MzAxMjctMC4yMDQxNjI2CgkJCWMxLjU0OTgzNTIsMCwyLjg5NDgzNjQsMC4yNTI3OTI0LDQuMDM3NzE5NywwLjc1NTA1MDdjMS4xNDE0Nzk1LDAuNTAyOTIyMSwyLjA5MTgyNzQsMS4yMjU3NzY3LDIuODUwMzExMywyLjE2Nzg4NDgKCQkJYzAuNzU3ODEyNSwwLjk0MjExNTgsMS4zMjkyMjM2LDIuMTMyMjYzMiwxLjcxMjkyMTEsMy41Njk3NzA4YzAuMzgzNjk3NSwxLjQzNzQ2MTksMC41NzQ4NTk2LDMuMTIyMjkxNiwwLjU3NDg1OTYsNS4wNTQ0ODkxCgkJCVY5OS40NDkwMjhIMzA1LjMyODcwNDh6Ii8+Cgk8L2c+Cgk8Zz4KCQk8Zz4KCQkJPHBvbHlnb24gY2xhc3M9InN0MSIgcG9pbnRzPSI5Ny4yNDg2NTcyLDAgMCwzNS40OTI2NjQzIDk3LjI1ODIzMjEsMTguMzEyNjUyNiA5Ny4yNTgyMzIxLDAgCQkJIi8+CgkJCTxwYXRoIGNsYXNzPSJzdDIiIGQ9Ik02Ni4zOTg4MTEzLDUwLjI1MTczMTlsLTguMzU3MDcwOSwxNi4wNTYzNTgzbC04LjMzNTgwNC0xNi4wNTYzNTgzSDMzLjM5MTk2NzhsMTcuMTg4MjQ3NywyOS43NjM5MTYKCQkJCVY5OS40NDkyMzRoMTQuNzEyMDIwOVY4MC4wMTU2NDc5bDE3LjIxMDg3NjUtMjkuNzYzOTE2SDY2LjM5ODgxMTN6IE0wLjg0ODMxMTQsNTAuMjUxNzMxOVY5OS40NDkyMzRoMzkuMzU3MDE3NVY4OC4xMzIyMTc0CgkJCQlIMTUuNjA0MTkzN3YtOC4xMTY1Njk1aDE3Ljc4Nzc3MzF2LTEwLjMyODk0OUgxNS42MDQxOTM3di04LjExOTk5MTNoMTkuNjc4MTY5M2wtNi41MjkwMjAzLTExLjMxNDk3NTdIMC44NDgzMTE0eiIvPgoJCTwvZz4KCTwvZz4KPC9nPgo8L3N2Zz4K"
        
        deck = HtmlDeck(theme)
        
        # Recreate the slides from test 1 structure
        deck.add_title_slide(
            title="EY Parthenon",
            subtitle="Strategic Consulting Excellence",
            authors=["EY Parthenon Team"],
            date="2024"
        )
        
        deck.add_content_slide(
            title="EY Parthenon Overview",
            subtitle="Leading Strategy Consulting Practice",
            num_columns=2,
            column_contents=[
                [
                    "Premier strategy consulting firm acquired by EY",
                    "Focus on transformational growth strategies",
                    "Deep sector expertise across industries",
                    "Global presence with local market knowledge"
                ],
                [
                    "Data-driven strategic insights",
                    "C-suite advisory services",
                    "Digital transformation capabilities",
                    "Merger & acquisition expertise"
                ]
            ]
        )
        
        deck.add_content_slide(
            title="Core Service Areas",
            subtitle="Comprehensive Strategy Consulting Portfolio",
            num_columns=3,
            column_contents=[
                [
                    "Strategy & Transformation",
                    "Corporate strategy",
                    "Business model innovation",
                    "Digital strategy"
                ],
                [
                    "Growth & Markets",
                    "Market entry strategies",
                    "Customer experience",
                    "Revenue optimization"
                ],
                [
                    "Transactions & Restructuring",
                    "M&A strategy",
                    "Due diligence",
                    "Post-merger integration"
                ]
            ]
        )
        
        # Add the custom slide with visualizations
        custom_html = """<div style="display: flex; justify-content: space-around; align-items: center; height: 400px;">
  <div style="text-align: center;">
    <div style="width: 150px; height: 150px; border-radius: 50%; background: linear-gradient(45deg, #2E86AB, #A23B72); display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: bold; margin: 0 auto;">
      Top 5
    </div>
    <h3>Global Strategy Consulting</h3>
    <p>Recognized leader in strategic advisory</p>
  </div>
  <div style="text-align: center;">
    <div style="width: 150px; height: 150px; border-radius: 50%; background: linear-gradient(45deg, #F18F01, #C73E1D); display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: bold; margin: 0 auto;">
      50+
    </div>
    <h3>Countries</h3>
    <p>Global reach with local expertise</p>
  </div>
  <div style="text-align: center;">
    <div style="width: 150px; height: 150px; border-radius: 50%; background: linear-gradient(45deg, #3E92CC, #0F4C75); display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: bold; margin: 0 auto;">
      1000+
    </div>
    <h3>Consultants</h3>
    <p>Expert team across industries</p>
  </div>
</div>"""
        
        deck.add_custom_html_slide(
            html_content=custom_html,
            title="Market Position & Growth",
            subtitle="Strategic Consulting Landscape"
        )
        
        deck.add_content_slide(
            title="Key Differentiators",
            subtitle="What Sets EY Parthenon Apart",
            num_columns=2,
            column_contents=[
                [
                    "EY Ecosystem Integration",
                    "Access to EY's global network",
                    "Tax, audit, and advisory synergies",
                    "Comprehensive client solutions"
                ],
                [
                    "Distinctive Approach",
                    "Fact-based strategic insights",
                    "Rapid implementation focus",
                    "Senior-level client engagement",
                    "Industry-specific expertise"
                ]
            ]
        )
        
        # Convert to PPTX
        converter = HtmlToPptxConverter(deck)
        result_path = asyncio.run(converter.convert_to_pptx(output_pptx_path, include_charts=True))
        
        print(f"✅ Conversion completed: {result_path}")
        return True
        
    except Exception as e:
        print(f"Error in conversion: {str(e)}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = test_html_to_pptx_conversion()
    sys.exit(0 if success else 1)