# Databricks App Configuration
# This file defines how the AI Slide Generator runs in Databricks Apps

# App metadata
name: "ai-slide-generator"
description: "AI-powered slide deck generator using LLMs and Genie"

# Startup command - install dependencies and run app
# Multiple workers enabled for multi-user concurrency
command:
  - "sh"
  - "-c"
  - |
    pip install -r requirements.txt && \
    python -m databricks_tellr_app.run

# Environment variables
env:
  - name: ENVIRONMENT
    value: "production"
  - name: DATABRICKS_HOST
    valueFrom: "system.databricks_host"  # Injected by Databricks
  - name: DATABRICKS_TOKEN
    valueFrom: "system.databricks_token"  # App service principal token
  - name: LOG_LEVEL
    value: "INFO"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  # Required for Google Slides OAuth credential/token encryption.
  # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  # - name: GOOGLE_OAUTH_ENCRYPTION_KEY
  #   value: "<your-fernet-key>"
  # Lakebase schema configuration
  # PGHOST and PGUSER are auto-set when database resource is attached
  - name: LAKEBASE_SCHEMA
    value: "app_data"

# Note: compute_size is set programmatically during deployment via the Databricks SDK
# Valid values configured in deployment.yaml: MEDIUM, LARGE, LIQUID
