"""Convert HTML slides to PowerPoint presentations.

This module provides functionality to convert HTML slide decks generated by
html_slides.py to PowerPoint (.pptx) format. It handles both text content
and visual elements like charts and graphics by using screenshot capture.

Based on the analysis in slide_export_charts_analysis.md, this implementation
focuses on chart-aware conversion with quality preservation for visualizations.
"""

from __future__ import annotations

import asyncio
import base64
import io
import re
from pathlib import Path
from typing import List, Optional, Tuple, Union
from dataclasses import dataclass

try:
    from playwright.async_api import async_playwright, Page
    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    PLAYWRIGHT_AVAILABLE = False

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_SHAPE
    PYTHON_PPTX_AVAILABLE = True
except ImportError:
    PYTHON_PPTX_AVAILABLE = False

from .html_slides import HtmlDeck, Slide


@dataclass
class ChartElement:
    """Represents a chart or visual element found in HTML slides."""
    selector: str
    slide_index: int
    element_type: str  # 'chart', 'svg', 'canvas', 'custom'
    screenshot_data: bytes = None
    width: int = 0
    height: int = 0


class HtmlToPptxConverter:
    """Converts HTML slides to PowerPoint format with chart preservation."""
    
    def __init__(self, html_deck: HtmlDeck):
        """Initialize converter with an HTML deck.
        
        Args:
            html_deck: The HtmlDeck instance to convert
        """
        if not PLAYWRIGHT_AVAILABLE:
            raise ImportError("Playwright is required for HTML to PPTX conversion. Install with: pip install playwright")
        
        if not PYTHON_PPTX_AVAILABLE:
            raise ImportError("python-pptx is required for PowerPoint generation. Install with: pip install python-pptx")
        
        self.html_deck = html_deck
        self.slides = html_deck._slides
        self.theme = html_deck.theme
        
    async def convert_to_pptx(self, output_path: str, include_charts: bool = True) -> str:
        """Convert HTML slides to PowerPoint format.
        
        Args:
            output_path: Path where the .pptx file will be saved
            include_charts: Whether to capture and include charts/visualizations
            
        Returns:
            Path to the saved PowerPoint file
        """
        # Create PowerPoint presentation
        prs = Presentation()
        
        # Set slide dimensions to 16:9 widescreen
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)
        
        if include_charts:
            # Use Playwright to capture charts and visual elements
            charts = await self._capture_charts()
        else:
            charts = []
        
        # Convert each slide
        for i, slide in enumerate(self.slides):
            await self._convert_slide(prs, slide, i, charts)
        
        # Save the presentation
        prs.save(output_path)
        return output_path
    
    async def _capture_charts(self) -> List[ChartElement]:
        """Capture charts and visual elements from HTML slides using Playwright."""
        charts = []
        
        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            
            # Set viewport to match slide dimensions
            await page.set_viewport_size({"width": 1920, "height": 1080})
            
            # Generate HTML content
            html_content = self.html_deck.to_html()
            
            # Load the HTML content
            await page.set_content(html_content)
            
            # Wait for content to load
            await page.wait_for_timeout(3000)
            
            # Find chart elements in the HTML (simplified approach)
            chart_selectors = [
                'div[style*="background: linear-gradient"]',  # Custom gradient charts
                'svg',  # SVG charts
                'canvas',  # Canvas charts
                '.chart-container',  # Chart containers
            ]
            
            # Look for charts across all slides
            for slide_idx, slide in enumerate(self.slides):
                for selector in chart_selectors:
                    elements = await page.query_selector_all(f'.reveal .slides section:nth-child({slide_idx + 1}) {selector}')
                    
                    for element in elements:
                        try:
                            # Check if element is visible and has content
                            is_visible = await element.is_visible()
                            if not is_visible:
                                continue
                            
                            # Get element dimensions
                            box = await element.bounding_box()
                            if not box or box['width'] < 50 or box['height'] < 50:
                                continue  # Skip small elements
                            
                            # Capture screenshot of the element
                            screenshot_data = await element.screenshot()
                            
                            chart = ChartElement(
                                selector=selector,
                                slide_index=slide_idx,
                                element_type=self._get_element_type(selector),
                                screenshot_data=screenshot_data,
                                width=int(box['width']),
                                height=int(box['height'])
                            )
                            charts.append(chart)
                        except Exception as e:
                            # Skip this element if there's an error
                            continue
            
            await browser.close()
        
        return charts
    
    def _get_element_type(self, selector: str) -> str:
        """Determine the type of chart element from its selector."""
        if selector == 'svg':
            return 'svg'
        elif selector == 'canvas':
            return 'canvas'
        elif 'chart' in selector.lower():
            return 'chart'
        else:
            return 'custom'
    
    async def _convert_slide(self, prs: Presentation, slide: Slide, slide_index: int, charts: List[ChartElement]) -> None:
        """Convert a single HTML slide to PowerPoint."""
        # Add a blank slide
        slide_layout = prs.slide_layouts[6]  # Blank layout
        ppt_slide = prs.slides.add_slide(slide_layout)
        
        # Get charts for this slide
        slide_charts = [c for c in charts if c.slide_index == slide_index]
        
        if slide.slide_type == "title":
            await self._convert_title_slide(ppt_slide, slide)
        elif slide.slide_type == "agenda":
            await self._convert_agenda_slide(ppt_slide, slide)
        elif slide.slide_type == "content":
            await self._convert_content_slide(ppt_slide, slide, slide_charts)
        elif slide.slide_type == "custom":
            await self._convert_custom_slide(ppt_slide, slide, slide_charts)
    
    async def _convert_title_slide(self, ppt_slide, slide: Slide) -> None:
        """Convert a title slide to PowerPoint."""
        # Add title
        title_box = ppt_slide.shapes.add_textbox(
            Inches(1), Inches(2), Inches(11), Inches(2)
        )
        title_frame = title_box.text_frame
        title_frame.text = slide.title
        
        # Style title
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(40)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(0, 0, 0)
        
        # Add subtitle
        if slide.subtitle:
            subtitle_box = ppt_slide.shapes.add_textbox(
                Inches(1), Inches(4), Inches(11), Inches(1)
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_frame.text = slide.subtitle
            
            # Style subtitle
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.font.size = Pt(24)
            subtitle_para.font.color.rgb = RGBColor(102, 163, 255)
        
        # Add byline (authors and date)
        authors = slide.metadata.get('authors', [])
        date = slide.metadata.get('date', '')
        if authors or date:
            authors_str = ", ".join(authors) if authors else ""
            byline = " • ".join([p for p in [authors_str, date] if p])
            
            byline_box = ppt_slide.shapes.add_textbox(
                Inches(1), Inches(5.5), Inches(11), Inches(1)
            )
            byline_frame = byline_box.text_frame
            byline_frame.text = byline
            
            # Style byline
            byline_para = byline_frame.paragraphs[0]
            byline_para.font.size = Pt(18)
            byline_para.font.color.rgb = RGBColor(80, 80, 80)
        
        # Add blue accent bar
        blue_bar = ppt_slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(1), Inches(1.5), Inches(1.2), Inches(0.1)
        )
        blue_bar.fill.solid()
        blue_bar.fill.fore_color.rgb = RGBColor(0, 122, 255)
        blue_bar.line.fill.background()
    
    async def _convert_agenda_slide(self, ppt_slide, slide: Slide) -> None:
        """Convert an agenda slide to PowerPoint."""
        # Add title
        title_box = ppt_slide.shapes.add_textbox(
            Inches(1), Inches(0.5), Inches(11), Inches(1)
        )
        title_frame = title_box.text_frame
        title_frame.text = slide.title or "Agenda"
        
        # Style title
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(0, 0, 0)
        
        # Add blue accent bar
        blue_bar = ppt_slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(1), Inches(1.6), Inches(1.2), Inches(0.1)
        )
        blue_bar.fill.solid()
        blue_bar.fill.fore_color.rgb = RGBColor(0, 122, 255)
        blue_bar.line.fill.background()
        
        # Add agenda items
        agenda_points = slide.metadata.get('agenda_points', [])
        if agenda_points:
            # Determine layout (single column vs two columns)
            if len(agenda_points) > 8:
                # Two column layout
                import math
                first_len = math.ceil(len(agenda_points) / 2)
                
                # First column
                self._add_agenda_column(ppt_slide, agenda_points[:first_len], 
                                      Inches(1), Inches(2.5), 1)
                
                # Second column
                self._add_agenda_column(ppt_slide, agenda_points[first_len:], 
                                      Inches(7), Inches(2.5), first_len + 1)
            else:
                # Single column layout
                self._add_agenda_column(ppt_slide, agenda_points, 
                                      Inches(1), Inches(2.5), 1)
    
    def _add_agenda_column(self, ppt_slide, items: List[str], left: Inches, top: Inches, start_num: int) -> None:
        """Add a column of agenda items to the slide."""
        for i, item in enumerate(items):
            y_pos = top + Inches(i * 0.8)
            
            # Add number circle (simplified as text for now)
            num_box = ppt_slide.shapes.add_textbox(
                left, y_pos, Inches(0.5), Inches(0.5)
            )
            num_frame = num_box.text_frame
            num_frame.text = str(start_num + i)
            
            # Style number
            num_para = num_frame.paragraphs[0]
            num_para.font.size = Pt(16)
            num_para.font.bold = True
            num_para.font.color.rgb = RGBColor(255, 255, 255)
            num_para.alignment = PP_ALIGN.CENTER
            
            # Add background color to number (approximate circle)
            num_box.fill.solid()
            num_box.fill.fore_color.rgb = RGBColor(0, 122, 255)
            
            # Add agenda item text
            text_box = ppt_slide.shapes.add_textbox(
                left + Inches(0.7), y_pos, Inches(5), Inches(0.6)
            )
            text_frame = text_box.text_frame
            text_frame.text = item
            
            # Style text
            text_para = text_frame.paragraphs[0]
            text_para.font.size = Pt(18)
            text_para.font.color.rgb = RGBColor(0, 0, 0)
    
    async def _convert_content_slide(self, ppt_slide, slide: Slide, charts: List[ChartElement]) -> None:
        """Convert a content slide to PowerPoint."""
        # Add title
        title_box = ppt_slide.shapes.add_textbox(
            Inches(1), Inches(0.5), Inches(11), Inches(1)
        )
        title_frame = title_box.text_frame
        title_frame.text = slide.title
        
        # Style title
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(0, 0, 0)
        
        # Add blue accent bar
        blue_bar = ppt_slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(1), Inches(1.6), Inches(1.2), Inches(0.1)
        )
        blue_bar.fill.solid()
        blue_bar.fill.fore_color.rgb = RGBColor(0, 122, 255)
        blue_bar.line.fill.background()
        
        # Add subtitle if present
        content_top = Inches(2.5)
        if slide.subtitle:
            subtitle_box = ppt_slide.shapes.add_textbox(
                Inches(1), Inches(2), Inches(11), Inches(0.5)
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_frame.text = slide.subtitle
            
            # Style subtitle
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.font.size = Pt(20)
            subtitle_para.font.color.rgb = RGBColor(102, 163, 255)
            
            content_top = Inches(3)
        
        # Add charts if present
        if charts:
            await self._add_charts_to_slide(ppt_slide, charts, content_top)
        else:
            # Add column content
            await self._add_column_content(ppt_slide, slide, content_top)
    
    async def _convert_custom_slide(self, ppt_slide, slide: Slide, charts: List[ChartElement]) -> None:
        """Convert a custom slide to PowerPoint."""
        content_top = Inches(0.5)
        
        # Add title if present
        if slide.title:
            title_box = ppt_slide.shapes.add_textbox(
                Inches(1), Inches(0.5), Inches(11), Inches(1)
            )
            title_frame = title_box.text_frame
            title_frame.text = slide.title
            
            # Style title
            title_para = title_frame.paragraphs[0]
            title_para.font.size = Pt(32)
            title_para.font.bold = True
            title_para.font.color.rgb = RGBColor(0, 0, 0)
            
            # Add blue accent bar
            blue_bar = ppt_slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                Inches(1), Inches(1.6), Inches(1.2), Inches(0.1)
            )
            blue_bar.fill.solid()
            blue_bar.fill.fore_color.rgb = RGBColor(0, 122, 255)
            blue_bar.line.fill.background()
            
            content_top = Inches(2.5)
        
        # Add subtitle if present
        if slide.subtitle:
            subtitle_box = ppt_slide.shapes.add_textbox(
                Inches(1), content_top, Inches(11), Inches(0.5)
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_frame.text = slide.subtitle
            
            # Style subtitle
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.font.size = Pt(20)
            subtitle_para.font.color.rgb = RGBColor(102, 163, 255)
            
            content_top += Inches(0.7)
        
        # Add charts if present
        if charts:
            await self._add_charts_to_slide(ppt_slide, charts, content_top)
        else:
            # Add custom HTML content as text (simplified)
            # Note: Full HTML parsing would require additional libraries
            text_content = self._extract_text_from_html(slide.content)
            if text_content:
                content_box = ppt_slide.shapes.add_textbox(
                    Inches(1), content_top, Inches(11), Inches(4)
                )
                content_frame = content_box.text_frame
                content_frame.text = text_content
                
                # Style content
                content_para = content_frame.paragraphs[0]
                content_para.font.size = Pt(16)
                content_para.font.color.rgb = RGBColor(20, 20, 20)
    
    async def _add_charts_to_slide(self, ppt_slide, charts: List[ChartElement], top_position: Inches) -> None:
        """Add chart images to the PowerPoint slide."""
        if not charts:
            return
        
        # Layout charts on the slide
        charts_per_row = min(2, len(charts))  # Maximum 2 charts per row
        chart_width = Inches(5.5)
        chart_height = Inches(3.5)
        
        for i, chart in enumerate(charts):
            row = i // charts_per_row
            col = i % charts_per_row
            
            left = Inches(1 + col * 6)
            top = top_position + Inches(row * 4)
            
            # Add the chart image
            img_stream = io.BytesIO(chart.screenshot_data)
            picture = ppt_slide.shapes.add_picture(
                img_stream, left, top, chart_width, chart_height
            )
    
    async def _add_column_content(self, ppt_slide, slide: Slide, top_position: Inches) -> None:
        """Add column content to the slide."""
        num_columns = slide.metadata.get('num_columns', 1)
        column_contents = slide.metadata.get('column_contents', [[]])
        
        if num_columns not in (1, 2, 3):
            num_columns = 1
        
        column_width = Inches(11 / num_columns - 0.5)
        
        for col_idx in range(num_columns):
            if col_idx < len(column_contents):
                items = column_contents[col_idx]
                
                left = Inches(1 + col_idx * (11 / num_columns))
                
                # Create bullet list
                content_box = ppt_slide.shapes.add_textbox(
                    left, top_position, column_width, Inches(4)
                )
                content_frame = content_box.text_frame
                
                for i, item in enumerate(items):
                    if i > 0:
                        para = content_frame.add_paragraph()
                    else:
                        para = content_frame.paragraphs[0]
                    
                    para.text = f"• {item}"
                    para.font.size = Pt(16)
                    para.font.color.rgb = RGBColor(20, 20, 20)
    
    def _extract_text_from_html(self, html_content: str) -> str:
        """Extract plain text from HTML content."""
        # Simple HTML tag removal (for basic conversion)
        # For production use, consider using BeautifulSoup or similar
        import re
        text = re.sub(r'<[^>]+>', '', html_content)
        text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
        text = text.replace('&quot;', '"').replace('&#39;', "'")
        return text.strip()


# Tool integration functions
def tool_export_to_pptx(deck: HtmlDeck, output_path: str, include_charts: bool = True) -> str:
    """Export HTML deck to PowerPoint format.
    
    Args:
        deck: The HtmlDeck instance to export
        output_path: Path where the .pptx file will be saved
        include_charts: Whether to capture and include charts/visualizations
        
    Returns:
        Success message with saved file path
    """
    async def _export():
        converter = HtmlToPptxConverter(deck)
        return await converter.convert_to_pptx(output_path, include_charts)
    
    # Run the async conversion
    try:
        result_path = asyncio.run(_export())
        return f"PowerPoint presentation saved to: {result_path}"
    except Exception as e:
        return f"Error exporting to PowerPoint: {str(e)}"


# Add tool definition to HtmlDeck
PPTX_EXPORT_TOOL = {
    "type": "function",
    "function": {
        "name": "tool_export_to_pptx",
        "description": "Export the current slide deck to PowerPoint (.pptx) format with chart preservation",
        "parameters": {
            "type": "object",
            "properties": {
                "output_path": {"type": "string", "description": "Path where the .pptx file will be saved"},
                "include_charts": {"type": "boolean", "description": "Whether to capture and include charts/visualizations", "default": True}
            },
            "required": ["output_path"],
            "additionalProperties": False
        }
    }
}